### ISSUE TITLE
Add helm hooks to run `ngrok diagnose` to check the network for connectivity

### ISSUE THREAD

**Issue by alex-bezek** [ngrok/ngrok-operator#445]
### Description

ngrok can sometimes be blocked by corporate firewalls https://ngrok.com/docs/guides/other-guides/running-behind-firewalls/
We can have people test their connection when we see they have specific errors in their logs, but it would be nice if the helm chart could test this for you when installing it. 

You can run the diagnose command in the ngrok agent container easily like this

```
apiVersion: batch/v1
kind: Job
metadata:
  name: ngrok-diagnose
spec:
  template:
    spec:
      containers:
        - name: ngrok-diagnose
          image: ngrok/ngrok:latest
          command: ["/bin/sh", "-c"]
          args: ["ngrok diagnose"]
      restartPolicy: Never
```

We should include this as a helm `pre-install` and `pre-upgrade` hooks as well as a helm test that could then be ran ad-hoc via `helm test ngrok-operator`

### Use Case

Inform users quickly of a specific network issue rather than them installing it and having to debug the logs to find network errors
