### ISSUE TITLE
Allow adding annotations to helm cluster roles

### ISSUE THREAD

**Issue by alex-bezek** [ngrok/ngrok-operator#88]
### Description

We should create a helm value that can be used to pass in arbitrary annotations that get added to the cluster role. 

### Use Case

With a CRD, a user/serviceaccount needs permission to access a specific resource. Out of the box, we can access a crd easily because auth is defaulted to the `system:masters` role. It is a best practice to not use this role and to create more locked down roles. 

Allowing annotations to be added to the cluster role would allow users to add annotations like these to easily give themselves access to the CRDs

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-cron-tabs-edit
  annotations:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
```
